---
    - name: MYSQL
      become: true
      remote_user: fabio.lima
      gather_facts: no
      become_method: sudo
      hosts: all
    
      pre_tasks:
        - name: 'install python2'
          raw: sudo apt-get -y install python-simplejson
    
      tasks:
            
        - name: Copiando script mysql
          copy:
            src: /home/fabio_lima/Documentos/infra-2.0/infra-stag-monitoramento/Ansible/script-mysql/mysql.sh
            dest: /home/fabio.lima/
            owner: fabio.lima
            group: fabio.lima
            mode: 0755

        - name: Copiando script carga zabbix
          copy:
            src: /home/fabio_lima/Documentos/infra-2.0/infra-stag-monitoramento/Ansible/script-mysql/carga-zabbix.sh
            dest: /home/fabio.lima/
            owner: fabio.lima
            group: fabio.lima
            mode: 0755

        - name: Executando script mysql
          shell: /home/fabio.lima/mysql.sh >> mysql.txt

        - name: Executando script carga zabbix
          shell: /home/fabio.lima/carga-zabbix.sh >> zabbix.txt
