- name: Install packages
  become: true
  remote_user: fabio.lima
  become_method: sudo
  gather_facts: no
  hosts: all

  pre_tasks:
    - name: Update
      raw: sudo apt-get update --fix-missing
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: locales PTBR-UTF8
      command: locale-gen pt_BR.UTF-8 
    
    # - name: Reconfigurando locales.
    #   command: dpkg-reconfigure locales
    
    - name: Ensure a locale exists
      locale_gen:
        name: pt_BR.UTF-8
        state: present
        
