---
- name: PHP
  become: true
  remote_user: fabio.lima
  gather_facts: no
  become_method: sudo
  hosts: all

  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson

  tasks:
    - name: Add PHP 7 PPA repository
      apt_repository:
        repo:  ppa:ondrej/php

    - name: Install PHP CLI
      become: true
      apt:
        name: php7.2-cli
        state: latest

    - name: Install PHP-FPM
      become: true
      apt:
        name: php7.2-fpm
        state: latest

    - name: Copiando arquivo .conf
      copy:
        src: /home/fabio_lima/Documentos/infra-2.0/infra-aws-blog-erico-prod/Ansible/php/ericorocha.conf
        dest: /etc/php/7.2/fpm/pool.d
        owner: deployer
        group: www-data
        mode: 0640
